# Generated by Django 5.0.4 on 2024-06-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='adress',
        ),
    ]
