# Generated by Django 5.0.4 on 2024-06-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_remove_order_product_name_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='orderitem',
        ),
    ]
