# Generated by Django 5.0.4 on 2024-06-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_alter_orderitem_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Доставка'), ('processing', 'В процессе отправки'), ('completed', 'Доставлено'), ('cancelled', 'Отменено')], default='processing', max_length=20),
        ),
    ]
