# Generated by Django 5.0.4 on 2024-06-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zakazi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('itogo', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'zakazi',
            },
        ),
    ]
