# Generated by Django 5.0.4 on 2024-06-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_accaunt', '0002_adress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zakazi',
        ),
    ]
