# Generated by Django 5.0.4 on 2024-06-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tempfavorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempFavorite',
        ),
    ]
