# Generated by Django 5.0.4 on 2024-06-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='user_username',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
