# Generated by Django 5.0.4 on 2024-06-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_review_user_review_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='feedback',
        ),
    ]
